feat(#12): add otel service name as an input or env var
inception-health/otel-export-trace-action pull request #13
Opened 2022-07-05 22:12 UTC by pragmaticivan

2022-07-06 21:45 UTC, v1v submitted a review, later dismissed

2022-07-22 20:25 UTC, nikordaris requested changes
We need to add a test case that validates the service name. You should be able to add the the test in `trace.test.ts` under the "resource attributes" test suite for a test case of "has service.name resource as otelServiceName" or something like that.

2022-07-22 20:25 UTC, nikordaris commented on src/tracing/trace.ts
>    workflowRunJobs: WorkflowRunJobs
```suggestion
export function createTracerProvider(
  otlpEndpoint: string,
  otlpHeaders: string,
  workflowRunJobs: WorkflowRunJobs,
  otelServiceName?: string | null | undefined,
```
Lets make this a non-breaking change to the API.

2022-07-22 20:25 UTC, nikordaris commented on src/tracing/trace.test.ts
> +        "",
We can remove all the empty strings in the tests after making the change non-breaking.

2022-07-22 20:26 UTC, nikordaris commented
Thanks for the contribution @pragmaticivan! I left a couple of comments. After those changes i think this will be good to merge in.

2022-07-24 16:33 UTC, pragmaticivan commented
Updated @nikordaris thanks!

2022-07-25 17:13 UTC, nikordaris submitted a review, later dismissed

2022-07-25 17:21 UTC, pragmaticivan commented
@nikordaris anything I need to fix? I just did run lint and test locally and they are all working.

2022-07-25 18:09 UTC, pragmaticivan commented
I've just updated my node version to exactly the one used in the CI (which uses latest and will probably come with unexpected side effects).

By changing the `minor` version I was able to replicate it locally. Some packages are due with updates, so that might also be a good time to get it in.

2022-07-25 21:25 UTC, nikordaris commented
@pragmaticivan ok, i think i fixed the build issues. if you pull the latest from main it should fix the build for this PR. apparently node 16.16 is stricter on version conflicts than 16.13

2022-07-25 21:33 UTC, ivan-santos-eq commented
@nikordaris rebased from the `main` branch.

2022-07-25 22:02 UTC, nikordaris submitted a review, later dismissed

2022-07-25 22:56 UTC, nikordaris commented
Ok the update dist action wasn't designed for forks. I need to fix that.

2022-07-26 21:43 UTC, nikordaris commented
@pragmaticivan ok i think i resolved the build issues. it looks like it created conflicts for you though. if you pull the latest, hopefully that will fix the build

2022-07-26 21:49 UTC, pragmaticivan commented
@nikordaris rebased

2022-07-26 22:13 UTC, merged